[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask-login>=0.6.3",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "flask-wtf>=1.2.2",
    "django>=5.2",
    "numpy>=2.2.5",
    "xgboost>=3.0.0",
    "scikit-learn>=1.6.1",
    "statsmodels>=0.14.4",
    "matplotlib>=3.10.1",
    "seaborn>=0.13.2",
    "pandas>=2.2.3",
]
